on:
  workflow_dispatch:
  pull_request:
    types: [ labeled ]

concurrency:
  group: ${{ contains(github.workflow,"main") }}-${{ github.head_ref }}
  cancel-in-progress: true
  
jobs:
  check-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sleep 5
      - run: echo "Done"
