on:
  workflow_dispatch:
  workflow_call:
    
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  release-notes-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sleep 5
      - run: echo "${{ github.workflow }}
